[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizers = true
optimizer_runs = 9999999
remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.4.0/",
]

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"
"@openzeppelin-contracts-upgradeable" = "5.4.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
sort_imports=true
